export enum AppRoutes {
  ROOT = "/",

  REGISTRATION_PAGE = "auth",
  OTP_LOGIN = "auth",
  LOGIN_PAGE = "auth/login",
  FORGOT_PASSWORD = "auth/forgot-password",
  RESET_PASSWORD = "auth/reset-password",
  SIGN_UP_GREET = "auth/sign-up-greet",
  LOGIN_WITH_PASSWORD = "/auth/password-login",
  SIGN_UP_OTP = "auth/sign-up-otp",
  UPDATE_PASSWORD = "auth/update-password",
  CREATE_PASSWORD = "auth/create-password",

  PROFILE_PAGE = "/admin/profile",
  EDIT_PROFILE = "/admin/profile/edit",

  ADMIN_LOGIN = "admin-auth/login",
  ADMIN_FORGOT_PASSWORD = "admin-auth/forgot-password",
  ADMIN_RESET_PASSWORD = "admin-auth/reset-password",
  ADMIN_USERS = "admin/admin-users",
  ADMIN_DASHBOARD = "admin/admin-dashboard",
  ADMIN_ADD_PROPERTY = "admin/admin-add-property",
  ADMIN_SETTINGS = "admin/admin-settings",
  ADMIN_PROPERTY = "admin/admin-property",
  ADMIN_PROFILE = "admin/admin-profile",
  ACTIVE_ACCOUNTS = "admin/admin-accounts/active",
  INVITED_ACCOUNTS = "admin/admin-accounts/invited",

  ON_BOARD_OWNER_TYPE = "on-board/owner-type",
  ON_BOARD_OWNER_COMPANY = "on-board/owner-detail/company",
  ON_BOARD_OWNER_INDIVIDUAL = "on-board/owner-detail/individual",
  ON_BOARD_PROPERTY_DETAIL = "on-board/property-detail",
  ON_BOARD_PROPERTY_TYPE = "on-board/property-type",
  ON_BOARD_GREET = "on-board/greet",

  PRIVACY_POLICY = "public/privacy-policy",
  TERMS_AND_CONDITIONS = "public/terms-and-conditions",

  DASHBOARD = "app/dashboard",
  USER_PROFILE = "app/profile",
  PROPERTY = "app/property",
  STAFFS = "app/staffs",
  UNITS = "app/units",
  USERS = "app/users",
  ADD_PROPERTY = "app/property/add",
  ACTIVE_RESIDENCES = "app/residences/active",
  INVITED_RESIDENCES = "app/residences/invited",
  NOTICE_BOARD = "app/notice-board",
  HELPDESK = "app/helpdesk",
  HELPDESK_CATEGORY = "app/helpdesk-category",
  INVOICES = "app/invoices",
  GATEPASS_REPORTS = "app/reports/gatepass",
  PANIC_REPORTS = "app/reports/panic-alert",
  PROPERTY_STAFF = "app/property-staff",
  COMMITTEE_MEMBER = "app/committee-member",
  POLICY = "app/policy",
  UNIT_SETTING = "app/unit-setting",
  INVOICE_SETTING = "app/invoice-setting",
  HELP_AND_SUPPORT = "app/help-and-support",

  SERVER_ERROR_PAGE = "server-error",
  ACCESS_DENIED = "access-denied",
  INVALID_LINK = "invalid-link",
  DEFAULT = "default-route",
}
