export enum StorageKeys {
  token = "token",
  PERMISSIONS = "permissions",
  USER_PERMISSIONS = "user_permissions",
  business = "business",
  DEFAULT_ROUTE = "default_route",
  USER = "user",
  SCOPES = "scopes",
  PER_PAGE = "per_page",
  HAS_PASSWORD = "has_password",
  COMMENTS_PER_PAGE = "comments_per_page",
  ALLOWED_BUSINESSES = "allowed_businesses",
  ALLOWED_BUILDINGS = "allowed_buildings",
  ACTIVE_BUSINESS = "active_business",
  ACTIVE_BUILDING = "active_building",
  ACTIVE_NEWS = "active_news",
  ACTIVE_TICKET = "active_ticket",
  ACTIVE_PROPERTY = "active_property",
  OWNER = "owner",
  CLIENTID = "client_id",
  REFRESH_TOKEN = "refreshToken",
  USERID = "user_id",
  REDIRECT_TO_ONBOARD_OWNER = "redirect_to_onboard_owner",
  REDIRECT_TO_ONBOARD_PROPERTY = "redirect_to_onboard_property",
  HAS_CHANGED_PASSWORD = "has_changed_password",
  ACCOUNT_TYPE = "account_type",
}
