import { IFineHistory } from "./fine-history";
import { IPayeeInfo } from "./payee-info";
import { IPayerInfo } from "./payer-info";
export interface IInvoice {
  id: string;
  invoiceNumber: string;
  referenceId: string;
  payerInfo: IPayerInfo;
  payeeInfo: IPayeeInfo;
  unitId: string;
  unitName: string;
  propertyId: string;
  invoiceType: string;
  invoiceStartFrom: string;
  invoiceEndTo: string;
  invoiceCreatedDate: string;
  initialAmount: number;
  includeTax: boolean;
  taxPercent: number;
  totalAmountWithoutTax: number;
  totalTaxAmountOnly: number;
  totalAmountWithTax: number;
  dueDays: number;
  fineHistories: IFineHistory[];
  includeFine: true;
  fineChargeFrequency: string;
  fineAmountConfigured: number;
  totalFineAmount: number;
  invoiceInterval: string;
  contractStartDate: string;
  contractEndDate: string;
  payedAt: string;
  paymentMethod: string;
  paymentStatus: string;
  transactionId: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  createdBy: string;
  updatedBy: string;
  deletedBy: string;
}
